# core/__init__.py
"""Core Package - Foundation components for the trading system."""
from .events import (
    EVENT_BUS,
    BarEvent,
    Event,
    EventBus,
    EventHandler,
    EventType,
    OrderEvent,
    RiskEvent,
    SignalEvent,
    TickEvent,
)
from .exceptions import (
    AuthenticationError,
    AuthorizationError,
    BrokerAuthenticationError,
    BrokerConnectionError,
    BrokerError,
    BrokerOrderError,
    CircuitBreakerError,
    DailyLossLimitError,
    DataError,
    DataFetchError,
    DataSourceUnavailableError,
    DataValidationError,
    DrawdownLimitError,
    InsufficientDataError,
    InsufficientFundsError,
    InsufficientPositionError,
    ModelError,
    ModelLoadError,
    ModelNotFoundError,
    OrderError,
    OrderRejectedError,
    OrderValidationError,
    PositionLimitError,
    PredictionError,
    RateLimitError,
    RiskError,
    RiskLimitBreachedError,
    TradingSecurityError,
    TradingError,
    TradingSystemError,
)

# Backward compatibility alias
SecurityError_ = TradingSecurityError
from .types import (
    Account,
    Fill,
    Order,
    OrderSide,
    OrderStatus,
    OrderType,
    Position,
    PositionSide,
    RiskLevel,
    RiskMetrics,
    SystemStatus,
    TradeSignal,
)

__all__ = [
    'OrderSide',
    'OrderType',
    'OrderStatus',
    'PositionSide',
    'RiskLevel',
    'SystemStatus',
    'Order',
    'Fill',
    'Position',
    'Account',
    'RiskMetrics',
    'TradeSignal',
    'Event',
    'EventType',
    'EventBus',
    'EventHandler',
    'TickEvent',
    'BarEvent',
    'OrderEvent',
    'SignalEvent',
    'RiskEvent',
    'EVENT_BUS',
    # Exceptions (abbreviated for space)
    'TradingSystemError',
    'DataError',
    'DataFetchError',
    'DataSourceUnavailableError',
    'DataValidationError',
    'InsufficientDataError',
    'TradingError',
    'OrderError',
    'OrderRejectedError',
    'OrderValidationError',
    'RiskError',
    'RiskLimitBreachedError',
    'DailyLossLimitError',
    'DrawdownLimitError',
    'CircuitBreakerError',
    'PositionLimitError',
    'InsufficientFundsError',
    'InsufficientPositionError',
    'BrokerError',
    'BrokerConnectionError',
    'BrokerAuthenticationError',
    'BrokerOrderError',
    'ModelError',
    'ModelNotFoundError',
    'ModelLoadError',
    'PredictionError',
    'AuthenticationError',
    'AuthorizationError',
    'RateLimitError',
    'TradingSecurityError',
    'SecurityError_',  # Backward compatibility alias
]
