#!/usr/bin/env python3
"""
China Network Setup Script for Trading Graph

This script helps users in mainland China quickly configure their environment
for optimal performance behind the Great Firewall.

Usage:
    python scripts/setup_china.py

What it does:
    1. Creates .env file with China-optimized settings
    2. Creates pip configuration for Chinese mirrors
    3. Tests network connectivity to Chinese data sources
    4. Provides installation instructions
"""

import os
import sys
from pathlib import Path


def print_header(text: str) -> None:
    """Print formatted header."""
    print("\n" + "=" * 70)
    print(f"  {text}")
    print("=" * 70 + "\n")


def print_success(text: str) -> None:
    """Print success message."""
    print(f"✓ {text}")


def print_warning(text: str) -> None:
    """Print warning message."""
    print(f"⚠ {text}")


def print_error(text: str) -> None:
    """Print error message."""
    print(f"✗ {text}")


def create_env_file() -> bool:
    """Create .env file with China-optimized settings."""
    print_header("Step 1: Creating .env Configuration")
    
    env_content = """# China Network Configuration for Trading Graph
# Generated by scripts/setup_china.py
# Last updated: 2026-02-26

# ================================================================
# CHINA NETWORK MODE
# ================================================================
TRADING_CHINA_DIRECT=1
TRADING_VPN=0

# ================================================================
# DATA SOURCES (China-accessible)
# ================================================================
TRADING_PRIMARY_SOURCE=tencent
TRADING_ENABLED_SOURCES=tencent,akshare,sina
TRADING_AKSHARE_ENABLED=1

# ================================================================
# CONNECTION SETTINGS (China-optimized)
# ================================================================
TRADING_CONNECTION_TIMEOUT=15
TRADING_REQUEST_TIMEOUT=12
TRADING_NETWORK_PROBE_TIMEOUT=4
TRADING_RETRY_ATTEMPTS=5
TRADING_RETRY_DELAY=2.0

# ================================================================
# CACHE SETTINGS
# ================================================================
TRADING_CACHE_TTL_HOURS=8
TRADING_MAX_MEMORY_CACHE_MB=1000

# ================================================================
# PERFORMANCE
# ================================================================
TRADING_PARALLEL_DOWNLOADS=6

# ================================================================
# OTHER SETTINGS (defaults)
# ================================================================
TRADING_MODE=simulation
TRADING_INITIAL_CAPITAL=100000
TRADING_LOG_LEVEL=INFO
"""
    
    env_path = Path(".env")
    
    if env_path.exists():
        backup_path = Path(".env.backup")
        try:
            # Backup existing .env
            with open(env_path, "r", encoding="utf-8") as f:
                content = f.read()
            with open(backup_path, "w", encoding="utf-8") as f:
                f.write(content)
            print_warning(f"Existing .env backed up to {backup_path}")
        except Exception as e:
            print_error(f"Failed to backup .env: {e}")
            return False
    
    try:
        with open(env_path, "w", encoding="utf-8") as f:
            f.write(env_content)
        print_success("Created .env with China-optimized settings")
        return True
    except Exception as e:
        print_error(f"Failed to create .env: {e}")
        return False


def create_pip_config() -> bool:
    """Create pip configuration for Chinese mirrors."""
    print_header("Step 2: Creating pip Configuration")
    
    # Determine pip config location
    if sys.platform == "win32":
        pip_dir = Path(os.environ.get("APPDATA", "")) / "pip"
        pip_conf = pip_dir / "pip.ini"
    else:
        pip_dir = Path.home() / ".config" / "pip"
        pip_conf = pip_dir / "pip.conf"
    
    # Also create local .pip/pip.ini
    local_pip_dir = Path(".pip")
    local_pip_conf = local_pip_dir / "pip.ini"
    
    pip_config = """[global]
index-url = https://pypi.tuna.tsinghua.edu.cn/simple
trusted-host = pypi.tuna.tsinghua.edu.cn
timeout = 60
retries = 5
progress-bar = on

[install]
trusted-host = pypi.tuna.tsinghua.edu.cn
"""
    
    # Create local configuration
    try:
        local_pip_dir.mkdir(exist_ok=True)
        with open(local_pip_conf, "w", encoding="utf-8") as f:
            f.write(pip_config)
        print_success(f"Created local pip config: {local_pip_conf}")
    except Exception as e:
        print_error(f"Failed to create local pip config: {e}")
        return False
    
    # Try to create global configuration
    try:
        pip_dir.mkdir(parents=True, exist_ok=True)
        with open(pip_conf, "w", encoding="utf-8") as f:
            f.write(pip_config)
        print_success(f"Created global pip config: {pip_conf}")
        print_success("All pip installs will now use Tsinghua mirror")
    except Exception as e:
        print_warning(f"Could not create global pip config: {e}")
        print_warning("Local .pip/pip.ini created - use with: pip install -c .pip/pip.ini <package>")
    
    return True


def test_network() -> bool:
    """Test network connectivity to Chinese data sources."""
    print_header("Step 3: Testing Network Connectivity")
    
    try:
        import requests
    except ImportError:
        print_error("requests not installed. Install with: pip install requests")
        return False
    
    # Test endpoints
    endpoints = {
        "Tencent (Quotes)": "https://qt.gtimg.cn/q=sh600519",
        "EastMoney (Data)": "https://82.push2.eastmoney.com/api/qt/clist/get?pn=1&pz=1",
        "Sina Finance": "https://finance.sina.com.cn",
        "Baidu": "https://www.baidu.com",
    }
    
    results = {}
    session = requests.Session()
    session.headers.update({
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    })
    
    for name, url in endpoints.items():
        try:
            resp = session.get(url, timeout=5)
            status = "✓ OK" if resp.status_code == 200 else f"✗ HTTP {resp.status_code}"
            results[name] = resp.status_code == 200
            print(f"  {name}: {status} ({resp.elapsed.total_seconds()*1000:.0f}ms)")
        except requests.Timeout:
            results[name] = False
            print(f"  {name}: ✗ Timeout")
        except requests.ConnectionError:
            results[name] = False
            print(f"  {name}: ✗ Connection Error")
        except Exception as e:
            results[name] = False
            print(f"  {name}: ✗ {type(e).__name__}")
    
    # Summary
    ok_count = sum(1 for v in results.values() if v)
    total = len(results)
    
    print(f"\n  Reachable: {ok_count}/{total}")
    
    if ok_count >= 3:
        print_success("Network connectivity looks good for China direct mode")
        return True
    elif ok_count >= 2:
        print_warning("Some endpoints unreachable - may need VPN for full functionality")
        return True
    else:
        print_error("Multiple endpoints failed - check your network connection")
        return False


def show_install_commands() -> None:
    """Show installation commands."""
    print_header("Step 4: Installation Commands")
    
    print("Run the following commands to install dependencies:\n")
    
    print("1. Install core dependencies (using Tsinghua mirror):")
    print("   pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple\n")
    
    print("2. Install AkShare (China A-share data):")
    print("   pip install akshare -i https://pypi.tuna.tsinghua.edu.cn/simple\n")
    
    print("3. Or install full China stack:")
    print("   pip install -e .[china-full] -i https://pypi.tuna.tsinghua.edu.cn/simple\n")
    
    print("4. Verify installation:")
    print("   python main.py --health\n")
    
    print("5. Run network diagnostics:")
    print("   python -m utils.china_diagnostics\n")


def show_next_steps() -> None:
    """Show next steps."""
    print_header("Next Steps")
    
    print("""
Configuration Complete!

Your environment is now configured for China network.

Quick Start:
  1. Install dependencies (see Step 4 above)
  2. Run: python main.py --health
  3. Run: python main.py --collect-news
  4. Run: python main.py --predict 600519

For more information, see:
  - docs/CHINA_SETUP.md - Detailed China setup guide
  - .env.china - Reference configuration
  - .pip/pip.ini - pip mirror configuration

Troubleshooting:
  - If you encounter timeout errors, increase TRADING_CONNECTION_TIMEOUT in .env
  - If data sources fail, check TRADING_ENABLED_SOURCES in .env
  - Run 'python main.py --doctor' for full diagnostics
  - Run 'python -m utils.china_diagnostics' for network tests
""")


def main() -> int:
    """Main entry point."""
    print_header("Trading Graph - China Network Setup")
    
    # Check Python version
    if sys.version_info < (3, 11):
        print_error("Python 3.11 or higher is required")
        print(f"Current version: {sys.version}")
        return 1
    
    print_success(f"Python version: {sys.version.split()[0]}")
    
    # Check current directory
    if not Path("main.py").exists():
        print_error("Please run this script from the project root directory")
        return 1
    
    print_success("Project directory verified")
    
    # Run setup steps
    steps = [
        ("Environment Configuration", create_env_file),
        ("pip Configuration", create_pip_config),
        ("Network Connectivity Test", test_network),
    ]
    
    results = []
    for name, func in steps:
        try:
            result = func()
            results.append(result)
        except Exception as e:
            print_error(f"{name} failed: {e}")
            results.append(False)
    
    # Show installation commands
    show_install_commands()
    
    # Show next steps
    show_next_steps()
    
    # Summary
    print_header("Setup Summary")
    
    if all(results):
        print_success("All setup steps completed successfully!")
        return 0
    else:
        print_warning("Some setup steps failed - review output above")
        print_warning("You can still proceed with installation, but may need to troubleshoot")
        return 0


if __name__ == "__main__":
    sys.exit(main())
